M48
; DRILL file {KiCad 9.0.2} date 2025-07-09T11:25:27+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-09T11:25:27+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X70.5Y-10.5
X70.57Y-21.0
X92.07Y-10.5
X92.07Y-21.0
M30
